# Generated by Django 4.2.21 on 2025-05-31 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completion_date',
        ),
        migrations.AddField(
            model_name='order',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата визита в сервисный центр'),
        ),
    ]
