# Generated by Django 4.2.21 on 2025-06-01 15:02

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_article_companyinfo_faq_promo_staffmember_vacancy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание обязанностей')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Сотрудник для контактов',
                'verbose_name_plural': 'Сотрудники для контактов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Термин словаря',
                'verbose_name_plural': 'Словарь терминов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='StaffMember',
        ),
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'ordering': ['order'], 'verbose_name': 'Информация о компании', 'verbose_name_plural': 'Информация о компании'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос и ответ', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='history',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='requisites',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='times_used',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='usage_limit',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='content',
            field=models.TextField(default='Информация о компании', verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='title',
            field=models.CharField(default='Сервисный центр', max_length=100, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='promo',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действует с'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='valid_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Действует до'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата от'),
        ),
    ]
