# Generated by Django 4.2.21 on 2025-06-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactemployee_dictionary_delete_staffmember_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order', 'title'], 'verbose_name': 'FAQ/Словарь', 'verbose_name_plural': 'FAQ/Словарь'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question',
        ),
        migrations.AddField(
            model_name='faq',
            name='content',
            field=models.TextField(default='', verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='faq',
            name='entry_type',
            field=models.CharField(choices=[('term', 'Термин словаря'), ('question', 'Вопрос-ответ')], default='term', max_length=10, verbose_name='Тип записи'),
        ),
        migrations.AddField(
            model_name='faq',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
